#!/usr/bin/env python3
"""Dump fixed tutorial dialogue lines for pre-baked TTS.

The manifest is intentionally separate from data/tts_fallback_manifest.json:
fallback TTS is keyed by NPC persona text, while tutorial TTS is keyed by
level_id + unit_id + displayed dialogue text.
"""

from __future__ import annotations

import argparse
import ast
import json
import pathlib
import re


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = "data/tutorial_tts_manifest.json"
UNIT_ID = "hero_li_chun"
DEFAULT_RESOURCE_ID = "seed-tts-2.0"
LEVEL_FILES = {
    "level1-1": "scenes/levels/level1-1/level1-1.gd",
    "level1-2": "scenes/levels/level1-2/level1-2.gd",
    "level1-3": "scenes/levels/level1-3/level1-3.gd",
    "level1-4": "scenes/levels/level1-4/level1-4.gd",
}

LINE_RE = re.compile(r"_lc_line\(\s*\"((?:[^\"\\]|\\.)*)\"\s*(?:,\s*[^)]*)?\)")
TAG_RE = re.compile(r"\[/?(?:b|i|u|s|center|right|left|wave|shake|rainbow|pulse|font_size|color)(?:=[^\]]*)?\]")

BASE_CONTEXT_HINT = (
    "李春是同一位温和沉稳的新手教程引导者，语气有古意但清楚口语化；"
    "这些台词属于同一段连续教学，请自然承接上下句，不要突然兴奋、压低、夸张停顿或重置情绪；"
    "当前是桥梁战棋教学关卡，正在指导玩家理解站位、HP、AP、CD、技能和阶段目标；"
    "HP、AP、CD 保持英文缩写读法，不要翻译成中文术语。"
)


def gd_unescape(value: str) -> str:
    # These GDScript string literals only use simple escapes that Python can
    # decode safely when wrapped back into a literal.
    return ast.literal_eval('"' + value + '"')


def strip_bbcode(text: str) -> str:
    return TAG_RE.sub("", text).strip()


def build_context_text(level_id: str, line_index: int, lines: list[str]) -> str:
    previous_text = lines[line_index - 2] if line_index > 1 else "无"
    current_text = lines[line_index - 1]
    next_text = lines[line_index] if line_index < len(lines) else "无"
    return (
        f"{BASE_CONTEXT_HINT}"
        f" 关卡：{level_id}。"
        f" 当前为第 {line_index}/{len(lines)} 句。"
        f" 上一句：{previous_text}"
        f" 当前句：{current_text}"
        f" 下一句：{next_text}"
    )


def read_hero_voice() -> str:
    src = (REPO_ROOT / "scripts/tts/voice_mapping.gd").read_text("utf-8")
    block_match = re.search(r'"hero_li_chun"\s*:\s*\{(?P<body>.*?)\n\s*\}', src, re.S)
    if not block_match:
        raise RuntimeError("找不到 VoiceMapping.VOICES[hero_li_chun]")
    voice_match = re.search(r'"voice"\s*:\s*"([^"]+)"', block_match.group("body"))
    if not voice_match:
        raise RuntimeError("hero_li_chun 缺 voice 字段")
    return voice_match.group(1)


def collect_items() -> list[dict]:
    voice = read_hero_voice()
    items: list[dict] = []
    for level_id, rel_path in LEVEL_FILES.items():
        text = (REPO_ROOT / rel_path).read_text("utf-8")
        display_lines = [gd_unescape(match.group(1)).strip() for match in LINE_RE.finditer(text)]
        tts_lines = [strip_bbcode(line) for line in display_lines]
        for idx, display_text in enumerate(display_lines, start=1):
            slug = "tutorial_%02d" % idx
            items.append(
                {
                    "level_id": level_id,
                    "unit_id": UNIT_ID,
                    "voice": voice,
                    "kind": "tutorial",
                    "slug": slug,
                    "context_group": f"{level_id}:tutorial",
                    "line_index": idx,
                    "text": display_text,
                    "tts_text": tts_lines[idx - 1],
                    "context_texts": [build_context_text(level_id, idx, tts_lines)],
                    "output": "assets/audio/tts_tutorial/%s/%s.mp3" % (level_id, slug),
                }
            )
    return items


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", default=OUTPUT)
    args = ap.parse_args()

    items = collect_items()
    doc = {
        "version": 1,
        "default_resource_id": DEFAULT_RESOURCE_ID,
        "_note": "auto-generated by tools/dump_tutorial_tts_manifest.py; rerun after tutorial dialogue text changes",
        "items": items,
    }
    out = REPO_ROOT / args.output
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, ensure_ascii=False, indent="\t") + "\n", "utf-8")

    counts: dict[str, int] = {}
    for item in items:
        counts[item["level_id"]] = counts.get(item["level_id"], 0) + 1
    print("[dump_tutorial_tts_manifest] wrote %s items=%d counts=%s" % (args.output, len(items), counts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
