extends SceneTree
## 把 NpcPersonas.PERSONAS 的 fallback_lines / qa_questions + VoiceMapping.VOICES 倒出成 manifest JSON。
## 用法：
##   godot --headless --path /path/to/Godot-game --script res://tools/dump_fallback_manifest.gd
##   ↑ 输出写到 data/tts_fallback_manifest.json
##
## Python 端 (generate_tts_fallbacks.py) 接管这个 JSON 后调火山 API 烤 mp3。
##
## 重新运行覆盖现有文件——但保留每个 item 已有的 slug（按 unit_id+kind+text 哈希稳定生成）。

const NpcPersonasScript := preload("res://scripts/llm/npc_personas.gd")
const VoiceMappingScript := preload("res://scripts/tts/voice_mapping.gd")

const OUTPUT_PATH := "res://data/tts_fallback_manifest.json"


func _init() -> void:
	var voices: Dictionary = VoiceMappingScript.VOICES
	var personas: Dictionary = NpcPersonasScript.PERSONAS
	var items: Array = []
	var stats := {"persona_total": 0, "with_fallback": 0, "lines_total": 0, "no_voice": 0}

	for unit_id_v in personas.keys():
		var unit_id: String = String(unit_id_v)
		var persona: Dictionary = personas[unit_id]
		stats["persona_total"] = int(stats["persona_total"]) + 1
		var fallback_lines: Variant = persona.get("fallback_lines", null)
		if not (fallback_lines is Dictionary):
			continue
		stats["with_fallback"] = int(stats["with_fallback"]) + 1
		# 解析 voice：voice_mapping VOICES 按 unit_id 索引；fallback 到 alias
		var voice_id: String = ""
		if voices.has(unit_id):
			voice_id = String(voices[unit_id].get("voice", ""))
		if voice_id.is_empty():
			stats["no_voice"] = int(stats["no_voice"]) + 1
			push_warning("[dump_manifest] %s 没找到 voice_mapping，跳过" % unit_id)
			continue

		# 遍历 fallback_lines: {kind: [text, ...]}
		for kind_v in (fallback_lines as Dictionary).keys():
			var kind: String = String(kind_v)
			var arr: Variant = (fallback_lines as Dictionary).get(kind, [])
			if not (arr is Array):
				continue
			var idx := 0
			for text_v in arr:
				idx += 1
				var text: String = String(text_v).strip_edges()
				if text.is_empty():
					continue   # 空字符串=本轮跳过类型，不需要 mp3
				var slug: String = "%s_%02d" % [kind, idx]
				items.append({
					"unit_id": unit_id,
					"voice":   voice_id,
					"kind":    kind,
					"text":    text,
					"slug":    slug,
					"output":  "assets/audio/tts_fallback/%s/%s.mp3" % [unit_id, slug],
				})
				stats["lines_total"] = int(stats["lines_total"]) + 1

		# bridge_tour 的 QA NPC 会先主动抛问题；这些固定问题也要有本地 fallback。
		var qa_question_items: Array[String] = []
		var qa_questions: Variant = persona.get("qa_questions", [])
		if qa_questions is Array:
			for q in qa_questions:
				var q_text := String(q).strip_edges()
				if not q_text.is_empty() and not qa_question_items.has(q_text):
					qa_question_items.append(q_text)
		var qa_question := String(persona.get("qa_question", "")).strip_edges()
		if not qa_question.is_empty() and not qa_question_items.has(qa_question):
			qa_question_items.append(qa_question)
		var q_idx := 0
		for text in qa_question_items:
			q_idx += 1
			var slug := "qa_question_%02d" % q_idx
			items.append({
				"unit_id": unit_id,
				"voice":   voice_id,
				"kind":    "qa_question",
				"text":    text,
				"slug":    slug,
				"output":  "assets/audio/tts_fallback/%s/%s.mp3" % [unit_id, slug],
			})
			stats["lines_total"] = int(stats["lines_total"]) + 1

	var doc: Dictionary = {
		"version": 1,
		"default_resource_id": "seed-tts-2.0",
		"_note": "auto-generated by tools/dump_fallback_manifest.gd; DO NOT hand-edit; modify npc_personas.fallback_lines instead and regenerate",
		"items": items,
	}
	var f: FileAccess = FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if f == null:
		push_error("无法写 %s" % OUTPUT_PATH)
		quit()
		return
	f.store_string(JSON.stringify(doc, "\t"))
	f.close()
	print("[dump_manifest] 写 %s" % OUTPUT_PATH)
	print("  personas=%d  with_fallback=%d  lines=%d  no_voice=%d"
		% [stats["persona_total"], stats["with_fallback"], stats["lines_total"], stats["no_voice"]])
	quit()
